name: Deploy CI package

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org/

            - name: Generate build number
              uses: einaregilsson/build-number@v2
              with:
                  token: ${{secrets.GITHUB_TOKEN}}

            - name: Publish to NPM
              run: npm publish --access=public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.npm_token}}
